package org.example.sqlite.jdbc.jdbc4

import org.example.sqlite.jdbc.SQLiteConnection
import org.example.sqlite.jdbc.jdbc3.JDBC3Statement
import java.sql.SQLException
import java.sql.Statement

open class JDBC4Statement(conn: SQLiteConnection) : JDBC3Statement(conn), Statement {
    // JDBC 4
    @Throws(ClassCastException::class)
    override fun <T> unwrap(iface: Class<T?>): T? {
        return iface.cast(this)
    }

    override fun isWrapperFor(iface: Class<*>): Boolean {
        return iface.isInstance(this)
    }

    private var closed = false

    @Throws(SQLException::class)
    override fun close() {
        super.close()
        closed = true // isClosed() should only return true when close() happened
    }

    override fun isClosed(): Boolean {
        return closed
    }

    @JvmField
    var closeOnCompletion: Boolean = false

    @Throws(SQLException::class)
    override fun closeOnCompletion() {
        if (closed) throw SQLException("statement is closed")
        closeOnCompletion = true
    }

    @Throws(SQLException::class)
    override fun isCloseOnCompletion(): Boolean {
        if (closed) throw SQLException("statement is closed")
        return closeOnCompletion
    }

    @Throws(SQLException::class)
    override fun setPoolable(poolable: Boolean) {
        // TODO Auto-generated method stub
    }

    @Throws(SQLException::class)
    override fun isPoolable(): Boolean {
        // TODO Auto-generated method stub
        return false
    }

    @Throws(SQLException::class)
    override fun executeLargeUpdate(sql: String): Long = super<JDBC3Statement>.executeLargeUpdate(sql)

    @Throws(SQLException::class)
    override fun executeLargeUpdate(sql: String, autoGeneratedKeys: Int): Long =
        super<JDBC3Statement>.executeLargeUpdate(sql, autoGeneratedKeys)

    @Throws(SQLException::class)
    override fun executeLargeUpdate(sql: String, colinds: IntArray): Long =
        super<JDBC3Statement>.executeLargeUpdate(sql, colinds)

    @Throws(SQLException::class)
    override fun executeLargeUpdate(sql: String, columnNames: Array<String>): Long =
        super<JDBC3Statement>.executeLargeUpdate(sql, columnNames)

    @Throws(SQLException::class)
    override fun executeLargeBatch(): LongArray = super<JDBC3Statement>.executeLargeBatch()

    @Throws(SQLException::class)
    override fun getLargeUpdateCount(): Long = super<JDBC3Statement>.getLargeUpdateCount()

    @Throws(SQLException::class)
    override fun getLargeMaxRows(): Long = super<JDBC3Statement>.getLargeMaxRows()

    @Throws(SQLException::class)
    override fun setLargeMaxRows(max: Long) {
        super<JDBC3Statement>.setLargeMaxRows(max)
    }
}
