spring.application.name=sqlol
spring.threads.virtual.enabled=true
java.awt.headless=true
reactor.schedulers.defaultBoundedElasticOnVirtualThreads=true
java.nio.channels.DefaultThreadPool.threadFactory=org.example.sqlol.SqlolApplication$VFactory
server.http2.enabled=true
spring.r2dbc.properties.protocol=file
spring.r2dbc.properties.driver=h2
spring.data.r2dbc.repositories.enabled=true
spring.data.jpa.repositories.enabled=true
spring.jpa.bootstrap=async
spring.jpa.database=h2
spring.datasource.hikari.threadFactory=org.example.sqlol.SqlolApplication$VFactory
spring.datasource.embedded-database-connection=h2
spring.h2.console.enabled=true
#debug=true
spring.h2.console.path=/h2-console
server.shutdown=immediate
spring.jpa.generate-ddl=true
spring.jpa.defer-datasource-initialization=true
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.url=jdbc:h2:async:./data/testdb;