<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>example</groupId>
    <artifactId>chicory-aot</artifactId>
    <version>1.0.0</version>

    <build>
        <plugins>
            <plugin>
                <groupId>com.dylibso.chicory</groupId>
                <artifactId>chicory-compiler-maven-plugin</artifactId>
                <version>1.7.5</version>
                <executions>
                    <execution>
                        <id>compile-wasm</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <wasmFile>${project.basedir}/sqlite3.wasm</wasmFile>
                            <name>com.example.wasm.Sqlite3Module</name>
                            <targetClassFolder>${project.basedir}/./build/classes</targetClassFolder>
                            <targetSourceFolder>${project.basedir}/./build/sources</targetSourceFolder>
                            <targetWasmFolder>${project.basedir}/./build/resources</targetWasmFolder>
                            <moduleInterface>com.example.wasm.Sqlite3Module</moduleInterface>

                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-wasm-jvmvfs</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <wasmFile>${project.basedir}/sqlite3-jvmvfs.wasm</wasmFile>
                            <name>com.example.wasm.JvmVfsModule</name>
                            <targetClassFolder>${project.basedir}/./build/classes</targetClassFolder>
                            <targetSourceFolder>${project.basedir}/./build/sources</targetSourceFolder>
                            <targetWasmFolder>${project.basedir}/./build/resources</targetWasmFolder>
                            <moduleInterface>com.example.wasm.JvmVfsModule</moduleInterface>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>