package org.example.sqlite.jdbc.jdbc3

import org.example.sqlite.jdbc.ExtendedCommand
import org.example.sqlite.jdbc.ExtendedCommand.SQLExtension
import org.example.sqlite.jdbc.SQLiteConnection
import org.example.sqlite.jdbc.core.Codes
import org.example.sqlite.jdbc.core.CoreStatement
import org.example.sqlite.jdbc.core.DB
import org.example.sqlite.jdbc.core.DB.ProgressObserver
import org.example.sqlite.jdbc.core.SafeStmtPtr.SafePtrFunction
import org.example.sqlite.jdbc.core.SafeStmtPtr.SafePtrIntFunction
import org.example.sqlite.jdbc.util.LoggerFactory.getLogger
import java.sql.*
import java.text.MessageFormat
import java.util.*
import java.util.function.Supplier
import kotlin.math.max

abstract class JDBC3Statement // PUBLIC INTERFACE /////////////////////////////////////////////
protected constructor(conn: SQLiteConnection) : CoreStatement(conn) {
    private var queryTimeout = 0 // in seconds, as per the JDBC spec
    @JvmField
    protected var updateCount: Long = 0
    @JvmField
    protected var exhaustedResults: Boolean = false

    /**
     * @see Statement.close
     */
    @Throws(SQLException::class)
    open fun close() {
        clearGeneratedKeys()
        internalClose()
    }

    /**
     * @see Statement.execute
     */
    @Throws(SQLException::class)
    open fun execute(sql: String): Boolean {
        internalClose()

        return this.withConnectionTimeout {
            val ext: SQLExtension? = ExtendedCommand.parse(sql)
            if (ext != null) {
                ext.execute(conn.database)

                return@withConnectionTimeout false
            }

            this@JDBC3Statement.sql = sql
            synchronized(conn) {
                conn.database.prepare(this@JDBC3Statement)
                val result: Boolean = exec()
                updateGeneratedKeys()
                updateCount = database.changes()
                exhaustedResults = false
                return@withConnectionTimeout result

            }

        }!!
    }

    /**
     * @see Statement.execute
     */
    @Throws(SQLException::class)
    open fun execute(sql: String, autoGeneratedKeys: Int): Boolean {
        return execute(sql)
    }

    /**
     * @param closeStmt Whether to close this statement when the resultset is closed.
     * @see Statement.executeQuery
     */
    @Throws(SQLException::class)
    public override fun executeQuery(sql: String, closeStmt: Boolean): ResultSet {
        rs.closeStmt = closeStmt

        return executeQuery(sql)
    }

    /**
     * @see Statement.executeQuery
     */
    @Throws(SQLException::class)
    open fun executeQuery(sql: String): ResultSet {
        internalClose()
        this.sql = sql

        return this.withConnectionTimeout<ResultSet?>(
            SQLCallable {
                conn.database.prepare(this@JDBC3Statement)

                if (!exec()) {
                    internalClose()
                    throw java.sql.SQLException(
                        "query does not return ResultSet", "SQLITE_DONE", Codes.Companion.SQLITE_DONE
                    )
                }
                exhaustedResults = false

                this.getResultSet()
            })!!
    }

    internal class BackupObserver : ProgressObserver {
        override fun progress(remaining: Int, pageCount: Int) {
            logger.info(
                Supplier {
                    MessageFormat.format(
                        "remaining:{0}, page count:{1}", remaining, pageCount
                    )
                })
        }

        companion object {
            private val logger = getLogger(BackupObserver::class.java)
        }
    }

    /**
     * @see Statement.executeUpdate
     */
    @Throws(SQLException::class)
    open fun executeUpdate(sql: String): Int {
        return executeLargeUpdate(sql).toInt()
    }

    /**
     * @see Statement.executeUpdate
     */
    @Throws(SQLException::class)
    open fun executeUpdate(sql: String, autoGeneratedKeys: Int): Int {
        return executeUpdate(sql)
    }

    /**
     * @see Statement.executeLargeUpdate
     */
    @Throws(SQLException::class)
    open fun executeLargeUpdate(sql: String): Long {
        internalClose()
        this.sql = sql

        return this.withConnectionTimeout<Long>(
            SQLCallable {
                val db: DB = conn.database
                var changes: kotlin.Long = 0
                val ext: SQLExtension? = ExtendedCommand.parse(sql)
                if (ext != null) {
                    // execute extended command
                    ext.execute(db)
                } else {
                    try {
                        kotlin.synchronized(db) {
                            changes = db.total_changes()
                            // directly invokes the exec API to support multiple SQL statements
                            val statusCode: kotlin.Int = db._exec(sql)
                            if (statusCode != Codes.Companion.SQLITE_OK) throw DB.newSQLException(statusCode, "")
                            updateGeneratedKeys()
                            changes = db.total_changes() - changes

                        }

                    } finally {
                        internalClose()
                    }
                }
                changes
            })!!
    }

    /**
     * @see Statement.executeLargeUpdate
     */
    @Throws(SQLException::class)
    open fun executeLargeUpdate(sql: String, autoGeneratedKeys: Int): Long {
        return executeLargeUpdate(sql)
    }

    /**
     * @see Statement.getResultSet
     */
    @Throws(SQLException::class)
    fun getResultSet(): ResultSet? {
            checkOpen()

            if (exhaustedResults) return null

            if (rs.isOpen()) {
                throw SQLException("ResultSet already requested")
            }

            if (pointer!!.safeRunInt<SQLException>(SafePtrIntFunction { obj: DB?, stmt: Long ->
                    obj!!.column_count(
                        stmt
                    )
                }) == 0) {
                return null
            }

            if (rs.colsMeta == null) {
                rs.colsMeta =
                    pointer!!.safeRun<Array<String>, SQLException>(SafePtrFunction { obj: DB?, stmt: Long ->
                        obj!!.column_names(stmt)
                    })
            }

            rs.cols = rs.colsMeta
            rs.emptyResultSet = !resultsWaiting
            rs.open = true
            resultsWaiting = false

            return rs as ResultSet
        }

    /**
     * This function has a complex behaviour best understood by carefully reading the JavaDoc for
     * getMoreResults() and considering the test StatementTest.execute().
     * 
     * @see Statement.getUpdateCount
     */
    @Throws(SQLException::class)
    fun getUpdateCount(): Int {
        return this.getLargeUpdateCount().toInt()
    }

    /**
     * This function has a complex behaviour best understood by carefully reading the JavaDoc for
     * getMoreResults() and considering the test StatementTest.execute().
     *
     * @see Statement.getLargeUpdateCount
     */
    @Throws(SQLException::class)
    open fun getLargeUpdateCount(): Long {
            val db = conn.database
            if (!pointer!!.isClosed() && !rs.isOpen() && !resultsWaiting && pointer!!.safeRunInt<SQLException>(
                    SafePtrIntFunction { obj: DB?, stmt: Long -> obj!!.column_count(stmt) }) == 0
            ) return updateCount
            return -1
        }

    /**
     * @see Statement.addBatch
     */
    @Throws(SQLException::class)
    open fun addBatch(sql: String) {
        internalClose()
        if (batch == null || batchPos + 1 >= batch!!.size) {
            val nb: Array<Any?> = arrayOfNulls<Any>(max(10, batchPos * 2))
            if (batch != null) System.arraycopy(batch, 0, nb, 0, batch!!.size)
            batch = nb
        }
        batch!![batchPos++] = sql
    }

    /**
     * @see Statement.clearBatch
     */
    @Throws(SQLException::class)
    open fun clearBatch() {
        batchPos = 0
        val localBatch = this.batch
        if (localBatch != null) for (i in localBatch.indices) localBatch[i] = null
    }

    /**
     * @see Statement.executeBatch
     */
    @Throws(SQLException::class)
    open fun executeBatch(): IntArray {
        return Arrays.stream(executeLargeBatch()).mapToInt { l: Long -> l.toInt() }.toArray()
    }

    /**
     * @see Statement.executeLargeBatch
     */
    @Throws(SQLException::class)
    open fun executeLargeBatch(): LongArray {
        // TODO: optimize
        internalClose()
        if (batch == null || batchPos == 0) return longArrayOf()

        val changes = LongArray(batchPos)
        val db = conn.database
        synchronized(db) {
            try {
                for (i in changes.indices) {
                    try {
                        this.sql = batch!![i] as String?
                        db.prepare(this)
                        changes[i] = db.executeUpdate(this, null)
                    } catch (e: SQLException) {
                        throw BatchUpdateException(
                            "batch entry " + i + ": " + e.message, null, 0, changes, e
                        )
                    } finally {
                        if (pointer != null) pointer!!.close()
                    }
                }
            } finally {
                clearBatch()
            }
        }

        return changes
    }

    /**
     * @see Statement.setCursorName
     */
    fun setCursorName(name: String) {}

    /**
     * @see Statement.getWarnings
     */
    @Throws(SQLException::class)
    fun getWarnings(): SQLWarning? = null

    /**
     * @see Statement.clearWarnings
     */
    @Throws(SQLException::class)
    fun clearWarnings() {
    }

    /**
     * @see Statement.getConnection
     */
    @Throws(SQLException::class)
    fun getConnection(): Connection = conn

    /**
     * @see Statement.cancel
     */
    @Throws(SQLException::class)
    fun cancel() {
        conn.database.interrupt()
    }

    /**
     * @see Statement.getQueryTimeout
     */
    @Throws(SQLException::class)
    fun getQueryTimeout(): Int {
        return queryTimeout
    }

    /**
     * @see Statement.setQueryTimeout
     */
    @Throws(SQLException::class)
    fun setQueryTimeout(seconds: Int) {
        if (seconds < 0) {
            throw SQLException("query timeout must be >= 0")
        }
        this.queryTimeout = seconds
    }

    // TODO: write test
    /**
     * @see Statement.getMaxRows
     */
    @Throws(SQLException::class)
    fun getMaxRows(): Int =// checkOpen();
        rs.maxRows.toInt()

    /**
     * @see Statement.setMaxRows
     */
    @Throws(SQLException::class)
    fun setMaxRows(max: Int) {
        this.setLargeMaxRows(max.toLong())
    }

    /**
     * @see Statement.getLargeMaxRows
     */
    @Throws(SQLException::class)
    open fun getLargeMaxRows(): Long =// checkOpen();
        rs.maxRows

    /**
     * @see Statement.setLargeMaxRows
     */
    @Throws(SQLException::class)
    open fun setLargeMaxRows(max: Long) {
        // checkOpen();
        if (max < 0) throw SQLException("max row count must be >= 0")
        rs.maxRows = max
    }

    /**
     * @see Statement.getMaxFieldSize
     */
    @Throws(SQLException::class)
    fun getMaxFieldSize(): Int = 0

    /**
     * @see Statement.setMaxFieldSize
     */
    @Throws(SQLException::class)
    fun setMaxFieldSize(max: Int) {
        if (max < 0) throw SQLException("max field size " + max + " cannot be negative")
    }

    /**
     * @see Statement.getFetchSize
     */
    @Throws(SQLException::class)
    fun getFetchSize(): Int = (rs as ResultSet).fetchSize

    /**
     * @see Statement.setFetchSize
     */
    @Throws(SQLException::class)
    fun setFetchSize(r: Int) {
        (rs as ResultSet).fetchSize = r
    }

    /**
     * @see Statement.getFetchDirection
     */
    @Throws(SQLException::class)
    fun getFetchDirection(): Int = ResultSet.FETCH_FORWARD

    /**
     * @see Statement.setFetchDirection
     */
    @Throws(SQLException::class)
    fun setFetchDirection(direction: Int) {
            when (direction) {
                ResultSet.FETCH_FORWARD, ResultSet.FETCH_REVERSE, ResultSet.FETCH_UNKNOWN -> {}
                else -> throw SQLException(
                    ("Unknown fetch direction "
                            + direction
                            + ". Must be one of FETCH_FORWARD, FETCH_REVERSE, or FETCH_UNKNOWN"
                            + " in java.sql.ResultSet")
                )
            }
        }

    /**
     * SQLite does not support multiple results from execute().
     *
     * @see Statement.getMoreResults
     */
    @Throws(SQLException::class)
    fun getMoreResults(): Boolean = getMoreResults(Statement.CLOSE_CURRENT_RESULT)

    /**
     * @see Statement.getMoreResults
     */
    @Throws(SQLException::class)
    fun getMoreResults(current: Int): Boolean {
        checkOpen()

        if (current == Statement.KEEP_CURRENT_RESULT || current == Statement.CLOSE_ALL_RESULTS) {
            throw SQLFeatureNotSupportedException(
                "Argument not supported: Statement.KEEP_CURRENT_RESULT or"
                        + " Statement.CLOSE_ALL_RESULTS"
            )
        }
        if (current != Statement.CLOSE_CURRENT_RESULT) {
            throw SQLException("Invalid argument")
        }

        // we support a single result set, close it
        rs.close()

        // as we don't have more result, change the update count to -1
        updateCount = -1
        exhaustedResults = true

        // always return false as we never have more results
        return false
    }

    /**
     * @see Statement.getResultSetConcurrency
     */
    @Throws(SQLException::class)
    fun getResultSetConcurrency(): Int = ResultSet.CONCUR_READ_ONLY

    /**
     * @see Statement.getResultSetHoldability
     */
    @Throws(SQLException::class)
    fun getResultSetHoldability(): Int = ResultSet.CLOSE_CURSORS_AT_COMMIT

    /**
     * @see Statement.getResultSetType
     */
    @Throws(SQLException::class)
    fun getResultSetType(): Int = ResultSet.TYPE_FORWARD_ONLY

    /**
     * @see Statement.setEscapeProcessing
     */
    fun setEscapeProcessing(enable: Boolean) {
        // no-op
        // This previously threw a SQLException as unsupported (added in
        // 44e559b74d53e2ca006a4638f57a4e6662d0f2c0),
        // but it's not allowed to do that according to the method documentation.
        // This had impacts when using CachedRowSet for example (Github #224).
        // The default value according to the JDBC spec is true, so changing this should not have
        // any impact.
    }

    protected open fun unsupported(): SQLException {
        return SQLFeatureNotSupportedException("not implemented by SQLite JDBC driver")
    }

    // Statement ////////////////////////////////////////////////////
    @Throws(SQLException::class)
    open fun execute(sql: String, colinds: IntArray): Boolean {
        throw unsupported()
    }

    @Throws(SQLException::class)
    open fun execute(sql: String, colnames: Array<String>): Boolean {
        throw unsupported()
    }

    @Throws(SQLException::class)
    open fun executeUpdate(sql: String, colinds: IntArray): Int {
        throw unsupported()
    }

    @Throws(SQLException::class)
    open fun executeUpdate(sql: String, cols: Array<String>): Int {
        throw unsupported()
    }

    @Throws(SQLException::class)
    open fun executeLargeUpdate(sql: String, colinds: IntArray): Long {
        throw unsupported()
    }

    @Throws(SQLException::class)
    open fun executeLargeUpdate(sql: String, cols: Array<String>): Long {
        throw unsupported()
    }

    @Throws(SQLException::class)
    protected fun <T> withConnectionTimeout(callable: SQLCallable<T>): T {
        val origBusyTimeout = conn.busyTimeout
        if (queryTimeout > 0) {
            // SQLite handles busy timeout in milliseconds, JDBC in seconds
            conn.busyTimeout = 1000 * queryTimeout
        }
        try {
            return callable.call()
        } finally {
            if (queryTimeout > 0) {
                // reset connection timeout to the original value
                conn.busyTimeout = origBusyTimeout
            }
        }
    }

    protected fun interface SQLCallable<T> {
        @Throws(SQLException::class)
        fun call(): T
    }
}
